[package]
name = "gtmpl_derive"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
gtmpl_value = { git = "https://github.com/fiji-flo/gtmpl_value.git" }
#gtmpl_value = { path = "../gtmpl_value" }
