[package]
name = "gtmpl_derive"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
description = "Derive for gtmpl_value"
license = "MIT"
repository = "https://github.com/fiji-flo/gtmpl_derive"
documentation = "https://docs.rs/crate/gtmpl_derive"
keywords = ["gtmpl_value", "gtmpl", "gtmpl-rust"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "tests/**/*.rs", "README.md", "LICENSE"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
gtmpl_value = { git = "https://github.com/fiji-flo/gtmpl_value.git" }
